global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8222']

  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order-service:8070']

  - job_name: 'product-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['product-service:8050']

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'payment-service:8060' ]  # adjust

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'notification-service:8030' ]  # adjust
